### ISSUE TITLE
Segfaults

### ISSUE THREAD

**Issue by blakejohnson** [timholy/IProfile.jl#14]
I keep running into an issue where running `@sprofile` on the same function several times causes Julia to segfault. I am not even sure where to start in finding the origin of this issue. I am running Mac OS 10.7.5. I rebuild Julia daily, and this problem has existed at least for a few weeks. I also rebuilt the Profile.jl library with `Pkg.runbuildscript("Profile")`.

If it would help to post the code I am running, I would be happy to do so.

**Comment by asterite** [comment]
We are facing similar issues in [Crystal](http://crystal-lang.org). We also believe it's a bug in libunwind and LLVM. We found this:

http://llvm.org/bugs/show_bug.cgi?id=20800

We applied the patch and use those binaries and it seems to be working fine, but now we tripped into this again so there might be more bugs. So I'm almost sure it has nothing to do with BLAS.

The worse thing is that it's hard to reproduce, for a given program it always crashes but we only get that with the compiler's source, and with small changes to the compiler's source it goes away or comes back so it's hard to find a minimal case.

**Comment by asterite** [comment]
BTW, it only happens on OSX. On Linux it always works fine.

**Comment by timholy** [comment]
I don't know whether this is still a problem for us (I can't test, since I don't have a Mac).

FYI, this profiler moved into julia base, and a potentially-relevant thread (very long, but with a happy resolution) is https://github.com/JuliaLang/julia/issues/3469. I suspect it's a separate issue, but I thought you should know about it .
